/** SVG paths via jsDelivr Simple Icons — only brands with matching icons. */
export const technologyLogos = [
  { name: "OpenAI", slug: "openai" },
  { name: "Anthropic", slug: "anthropic" },
  { name: "Google Gemini", slug: "googlegemini" },
  { name: "Hugging Face", slug: "huggingface" },
  { name: "LangChain", slug: "langchain" },
  { name: "NVIDIA", slug: "nvidia" },
  { name: "TensorFlow", slug: "tensorflow" },
  { name: "PyTorch", slug: "pytorch" },
  { name: "ElevenLabs", slug: "elevenlabs" },
  { name: "Deepgram", slug: "deepgram" },
  { name: "Replicate", slug: "replicate" },
  { name: "Ollama", slug: "ollama" },
  { name: "Mistral AI", slug: "mistralai" },
  { name: "Perplexity", slug: "perplexity" },
  { name: "CrewAI", slug: "crewai" },
  { name: "LiveKit", slug: "livekit" },
  { name: "Databricks", slug: "databricks" },
  { name: "Snowflake", slug: "snowflake" },
  { name: "Apache Kafka", slug: "apachekafka" },
  { name: "Apache Spark", slug: "apachespark" },
  { name: "Apache Airflow", slug: "apacheairflow" },
  { name: "Elasticsearch", slug: "elasticsearch" },
  { name: "Redis", slug: "redis" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "PostgreSQL", slug: "postgresql" },
  { name: "Neo4j", slug: "neo4j" },
  { name: "Qdrant", slug: "qdrant" },
  { name: "MLflow", slug: "mlflow" },
  { name: "Weights & Biases", slug: "weightsandbiases" },
  { name: "AWS", slug: "amazonaws" },
  { name: "Azure", slug: "microsoftazure" },
  { name: "Google Cloud", slug: "googlecloud" },
  { name: "Python", slug: "python" },
  { name: "TypeScript", slug: "typescript" },
  { name: "React", slug: "react" },
  { name: "Next.js", slug: "nextdotjs" },
  { name: "Node.js", slug: "nodedotjs" },
  { name: "FastAPI", slug: "fastapi" },
  { name: "Docker", slug: "docker" },
  { name: "Kubernetes", slug: "kubernetes" },
  { name: "Terraform", slug: "terraform" },
  { name: "Vercel", slug: "vercel" },
  { name: "Supabase", slug: "supabase" },
  { name: "n8n", slug: "n8n" },
  { name: "Ray", slug: "ray" },
  { name: "Modal", slug: "modal" },
  { name: "GitHub Copilot", slug: "githubcopilot" },
] as const;

export function techLogoUrl(slug: string) {
  return `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug}.svg`;
}
